# Generated by Django 4.0.1 on 2023-01-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=360)),
                ('price', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
