# Generated by Django 4.0.1 on 2023-01-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchmodel',
            name='description',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='fetchmodel',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fetchmodel',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fetchmodel',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fetchmodel',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fetchmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
