# Generated by Django 4.0.1 on 2023-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_fetchmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchmodel',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='fetchmodel',
            name='size',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
