# Generated by Django 4.0.1 on 2023-01-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_fetchmodel_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchmodel',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
