# Generated by Django 4.0.1 on 2023-01-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_fetchmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
